

SELECT * FROM Paciente
BEGIN TRANSACTION
	UPDATE Paciente SET telefono = '323219996' WHERE NOMBREPACIENTE = 'Manuel' -- hace un cambio 
if @@ROWCOUNT = 1
	COMMIT TRANSACTION -- confirma el cambio
ELSE 
	ROLLBACK TRANSACTION -- revierte el cambio 

SELECT * FROM Turno
BEGIN TRANSACTION
	DELETE FROM Turno WHERE ESTADODELTURNO = 1
if @@ROWCOUNT = 1
	COMMIT TRANSACTION -- confirma el cambio
ELSE 
	ROLLBACK TRANSACTION -- revierte el cambio 



BEGIN TRANSACTION
COMMIT TRANSACTION
ROLLBACK TRANSACTION 
